version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: celery_worker
    depends_on:
      - redis
    volumes:
      - .:/app
